//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormMain.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORY_食譜分類_LEVEL_TWO
    {
        public CATEGORY_食譜分類_LEVEL_TWO()
        {
            this.CATEGORY_食譜分類_LEVEL_THREE = new HashSet<CATEGORY_食譜分類_LEVEL_THREE>();
        }
    
        public int FEATURED_CATEGORY精選分類LEVEL_TWO_PK { get; set; }
        public string FEATURED_CATEGORY精選分類LEVEL_TWO_NAME名稱 { get; set; }
        public Nullable<int> LEVEL_ONE_FK { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_TIME { get; set; }
    
        public virtual CATEGORY_食譜分類_LEVEL_ONE CATEGORY_食譜分類_LEVEL_ONE { get; set; }
        public virtual ICollection<CATEGORY_食譜分類_LEVEL_THREE> CATEGORY_食譜分類_LEVEL_THREE { get; set; }
    }
}
