//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormMain.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECIPE_食譜_TMPTest
    {
        public string RECIPE食譜_PK { get; set; }
        public string RECIPE_NAME食譜名稱 { get; set; }
        public Nullable<System.DateTime> UPDATE_TIME更新時間 { get; set; }
        public Nullable<System.DateTime> PUBLISHED_TIME出版時間 { get; set; }
        public Nullable<int> FEATURED_CATEGORY精選分類LEVEL_ONE { get; set; }
        public Nullable<int> FEATURED_CATEGORY精選分類LEVEL_TWO { get; set; }
        public Nullable<int> FEATURED_CATEGORY精選分類LEVEL_THREE { get; set; }
        public Nullable<System.DateTime> PUBLISHED_TIME發表時間 { get; set; }
        public string AUTHOR_作者 { get; set; }
        public Nullable<int> LIKES_讚數 { get; set; }
        public string RECIPE_COVER { get; set; }
        public string SHORT_DESCRIPTION簡短說明 { get; set; }
        public string COST_MINUTES花費時間 { get; set; }
        public string AMOUNT_份量 { get; set; }
        public Nullable<int> CALORIES_熱量 { get; set; }
        public string TIPS_小撇步 { get; set; }
        public Nullable<int> FAVORITE_NUMBER收藏數 { get; set; }
    }
}
